apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-api-so
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-api-so
        app.kubernetes.io/part-of: dialogporten
        azure.workload.identity/use: "true"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: web-api-so
      containers:
        - name: web-api-so
          image: ghcr.io/altinn/dialogporten-webapi:set-by-ci
          envFrom:
            - configMapRef:
                name: web-api-so-runtime
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: Infrastructure__DialogDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: web-api-so-secrets
                  key: dialogportenAdoConnectionString
            - name: Infrastructure__Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: web-api-so-secrets
                  key: dialogportenRedisConnectionString
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: dialogporten-web-api-so
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.uid=$(POD_UID)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-api-so-runtime
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
data:
  DIALOGPORTEN_ENVIRONMENT: set-by-env
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-api-so-secrets
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dialogporten-azure-kv
  target:
    name: web-api-so-secrets
    creationPolicy: Owner
  data:
    - secretKey: dialogportenAdoConnectionString
      remoteRef:
        key: dialogportenAdoConnectionString
    - secretKey: dialogportenRedisConnectionString
      remoteRef:
        key: dialogportenRedisConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  selector:
    app.kubernetes.io/name: web-api-so
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-gateway
    namespace: traefik   
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: web-api-so
      port: 80
    filters:
    - requestHeaderModifier:
        set:
        - name: l5d-dst-override
          value: web-api-so.product-dialogporten.svc.cluster.local:80
      type: RequestHeaderModifier
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: web-api-so-ip-allowlist
    matches:
    - path:
        type: PathPrefix
        value: /dialogporten
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-api-so-ip-allowlist
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-api-so
  maxReplicas: 2
---
apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  name: web-api-so
  labels:
    app.kubernetes.io/name: web-api-so
    app.kubernetes.io/part-of: dialogporten
spec: {}
