apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: deploy-webhook
  namespace: product-dialogporten
spec:
  type: generic
  address: http://flux-dispatch.dis-platform.svc.cluster.local:8080/flux-events
