apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dialogporten
  namespace: flux-system
spec:
  interval: 10m
  provider: azure
  url: oci://altinncr.azurecr.io/dialogporten/dialogporten-sync
  ref:
    tag: main
