apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applicationidentity-secrets.yaml
  - external-secrets.yaml
  - feature-metrics-collector.yaml
  - linkerd-policies.yaml
  - runtime-config.yaml
configMapGenerator:
  - name: feature-metrics-collector-config
    files:
      - config.yaml=feature-metrics-collector-config.yaml
