apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apim/base
patches:
  - target:
      kind: Backend
      name: dialogporten-web-api-so
    patch: |
      - op: replace
        path: /spec/url
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten
  - target:
      kind: Api
      name: dialogporten-web-api-so
    patch: |
      - op: replace
        path: /spec/versions/0/serviceUrl
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten
  - target:
      kind: Backend
      name: dialogporten-web-api-eu
    patch: |
      - op: replace
        path: /spec/url
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten/enduser
  - target:
      kind: Api
      name: dialogporten-web-api-eu
    patch: |
      - op: replace
        path: /spec/versions/0/serviceUrl
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten/enduser
  - target:
      kind: Backend
      name: dialogporten-graphql
    patch: |
      - op: replace
        path: /spec/url
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten/graphql
  - target:
      kind: Api
      name: dialogporten-graphql
    patch: |
      - op: replace
        path: /spec/versions/0/serviceUrl
        value: https://dialogporten.prod.dis-core.altinn.cloud/dialogporten/graphql
