apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dialogporten-azure-kv
  labels:
    app.kubernetes.io/part-of: dialogporten
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${DIALOGPORTEN_KEY_VAULT_URL}
      serviceAccountRef:
        name: dialogporten-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dialogporten-secrets
  labels:
    app.kubernetes.io/part-of: dialogporten
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dialogporten-azure-kv
  target:
    name: dialogporten-secrets
    creationPolicy: Owner
  data:
    - secretKey: dialogportenAdoConnectionString
      remoteRef:
        key: dialogportenAdoConnectionString
    - secretKey: dialogportenRedisConnectionString
      remoteRef:
        key: dialogportenRedisConnectionString
