apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Kustomization
      name: dialogporten-apps
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: dialogporten-apps
        namespace: product-dialogporten
      spec:
        path: ./environments/prod
  - target:
      kind: OCIRepository
      name: dialogporten-manifests
    patch: |-
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: dialogporten-manifests
        namespace: product-dialogporten
      spec:
        ref:
          tag: prod
