apiVersion: apim.dis.altinn.cloud/v1alpha1
kind: Api
metadata:
  name: dialogporten-graphql
  labels:
    app.kubernetes.io/name: dialogporten-graphql
    app.kubernetes.io/part-of: dialogporten
spec:
  displayName: Dialogporten GraphQL
  description: Dialogporten GraphQL API
  path: dialogporten/graphql
  apiType: http
  versions:
    - name: v1
      displayName: v1
      isCurrent: true
      subscriptionRequired: false
      protocols:
        - https
      contentFormat: openapi+json
      content: |
        {
          "openapi": "3.0.1",
          "info": { "title": "dialogporten-graphql", "version": "1.0" },
          "paths": {
            "/*": {
              "get": { "operationId": "get", "responses": { "200": { "description": "" } } },
              "post": { "operationId": "post", "responses": { "200": { "description": "" } } },
              "put": { "operationId": "put", "responses": { "200": { "description": "" } } },
              "patch": { "operationId": "patch", "responses": { "200": { "description": "" } } },
              "delete": { "operationId": "delete", "responses": { "200": { "description": "" } } },
              "head": { "operationId": "head", "responses": { "200": { "description": "" } } },
              "options": { "operationId": "options", "responses": { "200": { "description": "" } } }
            }
          }
        }
      serviceUrl: set-by-env
