apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-api-so.yaml
  - web-api-eu.yaml
  - graphql.yaml
  - web-api-so-backend.yaml
  - web-api-eu-backend.yaml
  - graphql-backend.yaml
