apiVersion: apim.dis.altinn.cloud/v1alpha1
kind: Api
metadata:
  name: dialogporten-serviceowner
  labels:
    app.kubernetes.io/name: dialogporten-serviceowner
    app.kubernetes.io/part-of: dialogporten
spec:
  displayName: Dialogporten Serviceowner
  description: Dialogporten Service Owner API
  path: dialogporten/serviceowner
  apiType: http
  versions:
    - displayName: Dialogporten Serviceowner v1
      isCurrent: true
      subscriptionRequired: false
      protocols:
        - https
      contentFormat: openapi+json
      content: |
        {
          "openapi": "3.0.1",
          "info": { "title": "dialogporten-serviceowner", "version": "1.0" },
          "paths": {
            "/*": {
              "get": { "operationId": "get", "responses": { "200": { "description": "" } } },
              "post": { "operationId": "post", "responses": { "200": { "description": "" } } },
              "put": { "operationId": "put", "responses": { "200": { "description": "" } } },
              "patch": { "operationId": "patch", "responses": { "200": { "description": "" } } },
              "delete": { "operationId": "delete", "responses": { "200": { "description": "" } } },
              "head": { "operationId": "head", "responses": { "200": { "description": "" } } },
              "options": { "operationId": "options", "responses": { "200": { "description": "" } } }
            }
          }
        }
      serviceUrl: set-by-env
      policies:
        policyValues:
          - name: backendID
            idFromBackend:
              name: dialogporten-serviceowner
        policyContent: |
          <policies>
              <inbound>
                  <set-backend-service backend-id="{{.backendID}}" />
                  <base />
              </inbound>
              <backend>
                  <base />
              </backend>
              <outbound>
                  <base />
              </outbound>
              <on-error>
                  <base />
              </on-error>
          </policies>
        policyFormat: xml
