apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Kustomization
      name: dialogporten
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: dialogporten
        namespace: dialogporten
      spec:
        path: ./flux-system/at23
  - target:
      kind: Alert
      name: deploy-webhook
    patch: |-
      apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      metadata:
        name: deploy-webhook
        namespace: dialogporten
      spec:
        eventSources:
          - kind: Kustomization
            name: dialogporten-apps-at23
        eventMetadata:
          product: dialogporten
          env: at23
